trigger:
  - main

variables:
  MAVEN_OPTS: 'Xmx3072m'
  JAVA_VERSION: '17'
  MAVEN_POM_FILE: 'pom.xml'
  ARTIFACT_NAME: 'drop'

pool:
  vmImage: 'ubuntu-lastest'

stages:
  - stage: Build
    displayName: Compile e package
    jobs:
      - job: MavenBuild
        displayName: Build Maven Project
        steps:
          - task: JavaToolInstaller@0
            displayName: 'Install JDK'
            inputs:
              versionSpec: $(JAVA_VERSION)
              jdkArchitectureOption: 'x64'

          - task: Maven@3
            displayName: 'Executar Clean, Test e Package'
            inputs:
              mavenPomFile: $(MAVEN_POM_FILE)
              goals: 'clean install'
              publishJUnitResults: true
              testResultsFiles: '** /surefire-reports/TEST-*xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false

          - task: CopyFiles@2
            displayName: 'Copy Jar to staging directory'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: '**/target/*.jar'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish build artifact'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: '$ARTIFACT_NAME'