services:
  db:
    image: gvenzl/oracle-xe:latest
    container_name: Oracle
    ports:
      - '1521:1521'
    environment:
      ORACLE_PASSWORD: 12345
      ORACLE_SID: xe
      ORACLE_USER: system
    volumes:
      - data:/var/lib/oracle
    networks:
      - private_network
    healthcheck:
      test: ["CMD", "sqlplus", "-S", "/ AS SYSDBA", "<<EOF", "SELECT 1 FROM DUAL;", "EXIT;", "EOF"]
      interval: 10s
      timeout: 5s
      retries: 5

  api :
    container_name: esg-fiap-java
    ports:
      - '8080:8080'
    depends_on:
       db:
          condition: service_healthy
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=prd
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521:xe
      - SPRING_DATASOURCE_USERNAME=sys AS sysdba
      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      - public_network
      - private_network

volumes:
  data:

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge
