CREATE SEQUENCE IF NOT EXISTS SEQ_USUARIO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE T_USUARIO (
    id_usuario INTEGER DEFAULT SEQ_USUARIO.NEXTVAL PRIMARY KEY NOT NULL,
    -- NOME VARCHAR2(100) NOT NULL,
    LOGIN VARCHAR2(100) NOT NULL UNIQUE,
    SENHA VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(50) DEFAULT ON NULL 'USER'
);