CREATE SEQUENCE SEQ_CIDADE
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE T_CIDADE (
    id_cidade INTEGER DEFAULT SEQ_CIDADE.NEXTVAL PRIMARY KEY NOT NULL,
    nome_cidade VARCHAR2(100) NOT NULL,
    barrio VARCHAR2(100) NOT NULL,
    estado VARCHAR2(100) NOT NULL,
    cep VARCHAR2(100) NOT NULL
);
