CREATE SEQUENCE SEQ_POLUICAO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE T_POLUICAO (
    id_poluicao INTEGER DEFAULT SEQ_POLUICAO.NEXTVAL PRIMARY KEY NOT NULL,
    id_cidade NUMBER NOT NULL,
    co2 NUMBER(4,2) NOT NULL
);