CREATE SEQUENCE SEQ_CLIMA
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE T_CLIMA (
    id_clima INTEGER DEFAULT SEQ_CLIMA.NEXTVAL PRIMARY KEY NOT NULL,
    id_cidade NUMBER NOT NULL,
    temperatura NUMBER(4,2) NOT NULL,
    humidade NUMBER(4,2) NOT NULL
);