CREATE SEQUENCE SEQ_USUARIO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE T_USUARIO (
    id_usuario INTEGER DEFAULT SEQ_USUARIO.NEXTVAL PRIMARY KEY NOT NULL,
    login VARCHAR2(100) NOT NULL UNIQUE,
    senha VARCHAR2(100) NOT NULL,
    role VARCHAR2(50) DEFAULT ON NULL 'USER'
);