# Este workflow irá construir um projeto Java com Maven, e cache/restaurar dependências para melhorar o tempo de execução.
# Os testes de unidade serão executados usando o banco de dados em memória H2, o que é mais rápido e isolado.

name: Java CI with Maven

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4

      # 1. Configurar Docker Buildx
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 2. Autenticar no Google Cloud (Necessário para empurrar a imagem para o GCR)
      - name: 'Autenticar no GCP'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3. Configurar o Docker para o GCR
      - name: Configurar o Docker para o GCR
        run: |
          gcloud auth configure-docker gcr.io --quiet

      # 4. Construir e Empurrar para o GCR (Google Container Registry)
      - name: Construir e Empurrar Imagem para o GCR
        uses: docker/build-push-action@v3
        with:
          push: true
          # CRÍTICO: Imagem agora aponta para o GCR, usando o ID do projeto GCP
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/esg-fiap-java:${{ github.sha }}
          file: ./Dockerfile

  deploy-gcp:
    runs-on: ubuntu-latest
    needs: build # Garante que a imagem Docker foi criada e enviada
    environment:
      name: 'production'

    steps:
      - name: Checkout repositor
        uses: actions/checkout@v4
      # 1. Autenticação: Faz login no Google Cloud
      - name: 'Authenticate to GCP'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} # Usa a chave JSON do segredo

      # 2. Configuração: Instala a CLI do gcloud
      - name: 'Set up gcloud CLI'
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'

      # 3. Deploy: Executa a implantação
      - name: 'Deploy to App Engine'
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          # Especifica a imagem Docker completa a ser implantada (criada no job build)
          image_url: index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/esg-fiap-java:${{ github.sha }}
          # Usa o arquivo app.yaml para as configurações do ambiente flexível
          version: v${{ github.sha }}
          promote: true # Envia 100% do tráfego para a nova versão
